crm:
    resource: "@CRMBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

api:
    type: rest
    resource: "routing_api.yml"
    prefix:   /api

