post_index:
    path:     /
    defaults: { _controller: "CRMBundle:Post:index" }
    methods:  GET

post_show:
    path:     /{id}/show
    defaults: { _controller: "CRMBundle:Post:show" }
    methods:  GET

post_new:
    path:     /new
    defaults: { _controller: "CRMBundle:Post:new" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "CRMBundle:Post:edit" }
    methods:  [GET, POST]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "CRMBundle:Post:delete" }
    methods:  DELETE
